### ISSUE TITLE
NIST SP 800-63-3 document update

### ISSUE THREAD

**Issue by mlitzau** [GSA/ficam-arch#101]
#### Details of Issue: ####
In reference to the NIST SP 800-63-3 document, is there a time-frame when the official FICAM document will be updated?

**Comment by lachellel** [comment]
@mlitzau: 

- We're going through policies first and looking at our federations and trust frameworks
- The architecture use cases will need to be updated next - tentatively FY2018 Q2 (Jan - Mar)

**Comment by lachellel** [comment]
Addressed during architecture update working sessions  - closing
