### ISSUE TITLE
ICAM Services Framework Descriptions - Title Uniqueness

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#104]
#### Description of Issue: ####
Subcategory names should be unique and identifiable if they stand apart from their category title. Thus Creation should be Identity Creation, Maintenance should be Identity Maintenance (and Credential Maintenance). The others, such as [Credential] Issuance can at least be inferred.

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
