### ISSUE TITLE
ICAM Services Framework Descriptions - Main Category Descriptions

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#105]
#### Description of Issue: ####
Recommend that the main categories, Identity Management, Credential Management, Access Management, Federation, and Governance also have brief descriptions, as the subcategories do.

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
