### ISSUE TITLE
ICAM Services Framework Descriptions - Issuance Wording

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#106]
#### Description of Issue: ####
Issuance begins with “Transferring a credential to a person …”. The verb seems odd since normally credentials are created and assigned (i.e. issued) to persons.

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
+1

This might be an area where we deprecate _credential_ in favor of authenticator(s).  Review NIST and CDM docs to align.

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
