### ISSUE TITLE
ICAM Services Framework Descriptions -  Difference Between Entitlement Management and Provisioning

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#107]
#### Description of Issue: ####
There is too much overlap between Entitlement Management and Provisioning. The former includes “maintaining … permissions for a person …” and the latter includes “Linking and unlinking access permissions for a person …”? Is that not maintaining? Is there a clearer boundary between these two or should they be combined?

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
+1

- Provisioning was meant to be the establishment and management of accounts.  
- Entitlement management was meant to be the entitlements associated with those accounts.
- Combining or clarification is needed.

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
