### ISSUE TITLE
ICAM Services Framework Descriptions -  Federation Section Ordering

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#108]
#### Description of Issue: ####
Under Federation, should Credential Bridging be first, since generally authentication precedes creating assertions or exchanging attributes?

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
Comment: 

- Credential bridging should be removed (opinion)
- Update to be aligned with NIST documents

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
