### ISSUE TITLE
ICAM Services Framework Descriptions -  Logging vs. Auditing

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#109]
#### Description of Issue: ####
Auditing & Reporting covers the oversight of ICAM programs, but is silent on logging entity actions. Where should that go?

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
Comment: 
- This addition (logging entity actions) might be too detailed.  Logging, log review, and management are common security controls.

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - added / clarified  with context
