### ISSUE TITLE
ICAM Services Framework Descriptions -  Risk

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#110]
#### Description of Issue: ####
Where should risk accounted for? NIST 800-63-3 expands and encourages using measures that inform risk-based authentication and authorization decisions, but the closest connection is Credential Bridging, which covers only AALs and only for federated issuers. 

#### Details of Issue: ####
Maybe risk is covered under Policy Administration but I think it should be more explicit. A related issue is Trust, which must be in Federation, as it applies to the confidence in partners and their ICAM processes.

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
