### ISSUE TITLE
ICAM Services Framework Descriptions -  Administrative Corrections / Comments

### ISSUE THREAD

**Issue by jim-thomson** [GSA/ficam-arch#111]
#### Description of Issue: ####
1) There are inconsistent spellings of life cycle and lifecycle.
2) Policy Administration uses “rule sets”; I’ve seen this written as one word, too.
3) Registration uses the singular “person” and then uses the plural “them”. 

#### Link to the Content Page for Contributors: ####
https://arch.idmanagement.gov/services/

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
