### ISSUE TITLE
Identity Governance and Access Certifications

### ISSUE THREAD

**Issue by frank-briguglio-sp** [GSA/ficam-arch#114]
#### Description of Issue: ####
The FICAM Services Architecture does not include clear guidance on Access Certification/Attestation. As part of the CDM Phase 2 SailPoint deployment participating agencies now have access to the tools necessary to streamline this process and increase efficiencies and accuracy.

#### Details of Issue: ####
The SailPoint IdentityIQ Unified Governance Platform and Compliance Manager is being installed as the solution for the Master User Record. Compliance Manager enables agencies to;

Identity Warehouse and Resource Connectors
- Creates a single system of record for users, applications and entitlements with an extensive connector library for synchronizing data across on-prem and cloud apps

Policy Model
- Delivers access policy enforcement to enhance organizational security, lower risk, and meet regulatory compliance requirements

Role Model
- Simplifies the administration, request, review and fulfillment of user access by aligning access to job function 

Risk Model
- Identifies organizational risk caused by inappropriate access and enables prioritization of controls to mitigate the risk

Data-driven Workflow Engine
- Combines data-driven workflow approach across compliance and provisioning activities with a visual designer to simplify business process modeling

Business-friendly Access Certifications
- Reduces the cost and burden of compliance
- Simplifies campaign setup, admin and tracking
- Streamlines access review process by focusing on areas of high-risk
- Automates removal of excess access rights

Automated Policy Management
- Rapidly defines and deploys policies across applications  (e.g., SoD)
- Automatically scans, detects and remediates violations
- Leverages risk to prioritize policy enforcement 

Audit Reporting and Analytics
- Demonstrates compliance with pre-defined audit reports
- Creates transparency to IAM data across enterprise and cloud apps

#### References (Docs, Links, Files): ####

https://www.sailpoint.com/

DHS CDM Master User Record (MUR) Functional Description

#### If a New Page or Content is Needed, Expected Outcomes: ####

SailPoint will support the development of the necessary content

**Comment by lachellel** [comment]
- Vendor neutral content only 

- Aligned definitions with some CDM options during architecture update working sessions 

Closing.
