### ISSUE TITLE
https://arch.idmanagement.gov/usecases/ conflates credential federation and authentication federation

### ISSUE THREAD

**Issue by stvnewbold** [GSA/ficam-arch#122]
#### Description of Issue: ####
The use case overview at https://arch.idmanagement.gov/usecases/ conflates credential federation and authentication federation. Item 20 and Item 16 should never be in the same path. That is, if “Access” is applying credential federation, then Item 20 is superfluous because an external (federated) user is presenting a credential directly to Access. On the other hand, if authentication federation is applied, Item 16 is superfluous because an accepted authentication assertion is conveyed from Item 20 to Items 17/18.

#### Details of Issue: ####
Submitted for Jim Thomson from email, July 6 2018

#### References (Docs, Links, Files): ####
https://arch.idmanagement.gov/usecases/
Use cases 16 and 20

#### If a New Page or Content is Needed, Expected Outcomes: ####
Updates to content requested

**Comment by lachellel** [comment]
- Update or remove Use Case #20 
   - If update -> reuse NIST definitions and diagrams only
- Current #20 does conflate "identity" and authenticators
- Focus on the G2G scenarios (for relevance to most programs)

**Comment by lachellel** [comment]
addressed during architecture update working sessions - closing
