### ISSUE TITLE
Use Case #15 [Grant Access to a Protected Resource] should be updated for Assurance Levels consistent with NIST 800-63-3

### ISSUE THREAD

**Issue by stvnewbold** [GSA/ficam-arch#123]
#### Description of Issue: ####
Use Case #15 [Grant Access to a Protected Resource] should be updated for Assurance Levels consistent with NIST 800-63-3

#### Details of Issue: ####
Submitted for Jim Thomson, from email July 6, 2018

**Comment by lachellel** [comment]
use cases simplified per architecture update working sessions - closing
