### ISSUE TITLE
Use case #20 [Accept Credentials in a Federation] should be revisited to use terms consistent with NIST 800-63-3. 

### ISSUE THREAD

**Issue by stvnewbold** [GSA/ficam-arch#124]
#### Description of Issue: ####

Use case #20 [Accept Credentials in a Federation] should be revisited to use terms consistent with NIST 800-63-3. Note that “validate” and “verify” appear to be used interchangeably. Also, “verification assertion” is not a NIST 800-63C term. This flow is not what’s portrayed in the user case overview, although I appreciate that you can’t show all of the detail.
#### Details of Issue: ####

Submitted for Jim Thomson, via email July 6, 2018

**Comment by lachellel** [comment]
use cases simplified per architecture update working sessions - closing
