### ISSUE TITLE
Mobile Image and Text Rendering

### ISSUE THREAD

**Issue by weirdscience** [GSA/ficam-arch#13]
The text rendering when viewing the page on a mobile device resizes to whatever size of the image. See attached. Difficult when reading on a mobile device and something to keep in mind when adding larger images.

![image1](https://cloud.githubusercontent.com/assets/7793270/11251281/966cd8ec-8dfe-11e5-91d8-29713462b5f5.PNG)

![image2](https://cloud.githubusercontent.com/assets/7793270/11251282/966ff252-8dfe-11e5-9249-085deb43b43b.PNG)

**Comment by lachellel** [comment]
Looking into how we can make these more responsive...

**Comment by lachellel** [comment]
#54 
added responsiveness for mobile
We can improve for text and making more succinct; but images should be fixed, as well as Menu added to the top rather than inline
please check and provide feedback!
