### ISSUE TITLE
Use case 4: LOA4 + biometrics

### ISSUE THREAD

**Issue by malverdip** [GSA/ficam-arch#138]
#### Description of Issue: ####
Step 6 is the capture of biometric modalities. This step is performed after the steps for the validation of the identity is performed. This assumes that the validation of the identity can we done with a government issued ID and additional information provided, such as an account number.
I'm a first time contributor, so I will try to fill this out as best as I can.

#### Details of Issue: ####
The last step in LOA4 is the capture of biometric modalities to increase the level of non-repudiation. There is a practice in many countries where a government agency has biometric information of its citizens and is capable of providing biometric comprisson services to validate the identity of a person, and sometimes a national ID is issued. We should be aiming at this goal. Currently, that agency doesn't exist in the US, but we can use other agency to perform the same task. Additionally, there are identitiy sources that can be used to perform this same task. So, instead of verifying a government issued ID or an account number only, we can include the biometric verification of the identity.
Additionally, the governement agency itself can perform a biometric identification (1:N search) to reduce the possibility of having duplicated identity records. This task, deduplication of digital identity records, should be mandatory for LOA4. This is closely related to use case 5, as a match result to avoid deduplication should include the resolution of a possible biometric match.

#### References (Docs, Links, Files): ####
https://arch.idmanagement.gov/usecases/14_proofidentityloa4/

#### If a New Page or Content is Needed, Expected Outcomes: ####
New content recomendation.
Use case 4 should have biometric data captured in step 3.
Use case 4 should have biometric data verification in step 4.
Use case 4 should have a new step 5 for biometric identification, internal and external, to avoid DIR duplication. This would replace the current step 5 for confirmation, and move it to step 6.
Use case 4 should have a new step 6 for confirmation. This would replace the current step 6 for biometric capture. The current step 6 for biometric capture should be eliminated.

Expeted outcomes.
An increased level of assurance on the identities managed by the system. Additional features to verify identities.
I would recomend a similar analysis for use case 8.

**Comment by lachellel** [comment]
- addressed during architecture update working sessions  - replacing with simpler use cases (more generic)
- aligning with 800-63-3 (generic)
- closing

(great detailed comment!  appreciated!)
