### ISSUE TITLE
Add custom 404

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-arch#156]
#### Description of Issue: ####
We are proposing changing a URI (/applications to /components)

#### Details of Issue: ####
If we make this change and there are embedded links in other docs, we should include an updated/custom 404 as well

#### References (Docs, Links, Files): ####

It doesn't seem like we added a custom 404 yet to this repo. 
Simple example:  https://github.com/GSA/fpki-guides/blob/staging/404.md
Federalist guide for custom 404's: https://federalist.18f.gov/documentation/customization/

**Comment by idmken** [comment]
Included in new playbooks site.
