### ISSUE TITLE
Update styles to USWDS 2.x

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-arch#157]
#### Description of Issue: ####
Update styles and template to use USWDS 2.x

#### Details of Issue: ####
Old, old version of USWDS (0.9?) currently in use

#### References (Docs, Links, Files): ####
https://designsystem.digital.gov/

#### If a New Page or Content is Needed, Expected Outcomes: ####
This is a medium effort.  
The navigation (sub and side) and all assets in _includes need to reference newer styles.  Clean assets, etc.

**Comment by idmken** [comment]
Using on new playbooks site.
