### ISSUE TITLE
Goals & Objectives: Goal 1.2 (spelling mistake?)

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-arch#16]
Goal 1.2 in the Diagram states: 

> Enable Agencies to establish and manage prove, trusted identities for all system users

Should be:

> Enable Agencies to establish and manage **proven**, trusted identities for all system users

**Comment by lachellel** [comment]
incorporated in #21 and #22

**Comment by jim-thomson** [comment]
Sure. typo.
