### ISSUE TITLE
federation services

### ISSUE THREAD

**Issue by rossfoardg** [GSA/ficam-arch#162]
#### Description of Issue: ####
The use of the title "Authentication Broker" in the Federation sub-service does not align well with NIST SP800-63-3c.

#### Details of Issue: ####
I recommend using a term from 800-63-3c to describe the generation of the assertion. Perhaps title this simply "Assertions" or "Federation Protocols".

#### References (Docs, Links, Files): ####
https://pages.nist.gov/800-63-3/sp800-63c.html#assertions

**Comment by sarahdobson** [comment]
Disagree - assertions are not a service.
