### ISSUE TITLE
Consolidated Comments

### ISSUE THREAD

**Issue by RebeccaNielsen** [GSA/ficam-arch#166]
Attached please find consolidated comments from the Federal PKI Management Authority team.

[Comments on arch.idmanagement.gov.docx](https://github.com/GSA/ficam-arch/files/5423627/Comments.on.arch.idmanagement.gov.docx)

**Comment by lachellel** [comment]
@sarahdobson 
time permitting, can you break out the word doc into consolidated issues by type and section? 

I did a quick initial review.  Some items can be addressed; other items were addressed in the initial work sessions.  I can help point to the reasons from some agency feedback and notes (i.e. moving provisioning was a discussion topic, focusing on enterprise IAM versus CIAM which has different patterns and rules for agencies, etc). 

And the long and arduous journey around credential vs authenticators... 👍

**Comment by RebeccaNielsen** [comment]
I'm not sure what you mean "by type and section." All comments are labeled
by section. The GitHub interface is much too time consuming to rekey every
comment as a separate entry.

Rebecca

**Comment by lachellel** [comment]
@RebeccaNielsen - Its for @sarahdobson to break out.  Not asking you to. 

Not separate entries but so we label by section.

I also have scripts for large files 👍

**Comment by sarahdobson** [comment]
These comments have been moved to issues #168, #169, and #170.
