### ISSUE TITLE
Goals & Objectives: Goal 2.1

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-arch#17]
Current states in diagram:

> Automate information discover and access across the Federal Government in all security domains

Should be?

> Automate information **discovery** and access across the Federal Government in all security domains

**Comment by lachellel** [comment]
incorporated in #21 and #22

**Comment by jim-thomson** [comment]
Sure, but for something like this, why not just change it? We shouldn't be using this forum for typos.

**Comment by lachellel** [comment]
because i don't have the source images!  we need to drop the source files
into the repository so anyone can change and submit the change!

**Comment by jim-thomson** [comment]
Ohhh! I thought you just liked bureaucratic, online paperwork.  [cid:image004.png@01D1336E.27983280]
