### ISSUE TITLE
Content Feedback - FPKIMA

### ISSUE THREAD

**Issue by sarahdobson** [GSA/ficam-arch#170]
**General Comments**

1. The scope of FICAM needs to be broadened significantly beyond federal agency employees and contractors. The scope must include mission partners and constituents, and should also be expanded to include non-person entities.
2. The FICAM Architecture shouldn’t only be focused on enterprise solutions, it should provide a framework for implementing ICAM across the Federal Government, which includes Federal-government-wide services, department or agency-wide services, as well as component and local services.

**Introduction**

3. Is this a playbook or is this the architecture itself? The introductory sentence says this is a playbook, but there is no reference to any other document.
4. ICAM isn’t just about enterprise level services. Recommend removing the term “enterprise” from the definitions. The FICAM should support enterprise level services, but should also include community of interest and local level services that may be needed to achieve mission objectives.
5. Disagree with the definition of identity management, “Identity Management is how an agency uses attributes to establish and maintain enterprise identities for employees and contractors.” Identity management isn’t about how attributes are used, it’s about collecting, verifying, and managing attributes and making them available to support access decisions. Using attributes is part of authorization and should be covered in access management.
6. The definition of federation is overly restrictive. Federation is not only about agencies interoperating with other agencies, it is also about interoperating with mission partners and constituents. Federation should encompass these communities as well.
7. The introduction has two different definitions of ICAM – there is on at the top, then a different one in the section “What is ICAM.” The top definition seems to better align with how the term is being used, recommend not redefining it.
8. Consider rewording the statement of what the FICAM Architecture is for. “The FICAM Architecture is for agency personnel looking for federal information technology resources.” Seems overly restrictive. The FICAM architecture isn’t about people looking for IT resources, it should support governance, deployment, and use of ICAM services.
9. I don’t understand why the focus of the FICAM Architecture on IT users. Successful ICAM deployment depends on more than just IT, it requires business/mission owners to understand their access rules, it requires organization management to support ICAM as a critical organizational need, and it requires the support of every end user. Need a better definition.
10. The background statement is confusing. What is the status of the FICAM Roadmap? Is it cancelled? Is it superseded by this FICAM Architecture? Is it still a requirement that is being updated? Need to clearly tell the reader about the history and the current state.

**Goals and Objectives**

11. Goal 2, “Enable missions to efficiently deliver services to federal and contractor employees and resources.” Doesn’t make sense. Missions don’t deliver services, agencies deliver services to achieve mission objectives. Not sure what “and resources” belongs with. Are missions delivering services and resources? Or are missions delivering services to resources? Need to reword.
12. ICAM isn’t just about federal employees and contractors. ICAM needs to support mission partners and constituents as well. Need to refocus to include all communities.
13. 3.2 & 3.3 objectives appear to have a pre-conceived conclusion bias rather than potential for an agency to arrive at other more cost-effective results during the Evaluation & rationalization process

**Services Framework - Identity Management**

14. Identity proofing, which is defined as “Verify an identity’s attributes in order to issue a credential.” Should be part of Credential management, not identity management. Identity management should be focused on collecting, verifying, and maintaining attributes. Identity proofing is performed to connect a digital identity to a real world entity in order to issue that real world entity a credential linked to the digital identity.
15. Disagree with moving provisioning from access management to identity management. While managing attributes is part of identity management, provisioning accounts isn’t generally something that is done using services focused on identity management. Recommend including attribute management as part of identity management but putting account provisioning back in access management.
16. Recommend using the term “identity resolution” instead of “identity aggregation.”
17. The concept of “deactivation” and “expire” are confusing in the identity management section. There is a statement that identities do not expire, but deactivation is one of the identity management services. Need to connect these terms together somehow.
18. Disagree with the statement that “Agencies should manage identity attributes as centrally as possible.” Not all attributes should be centrally managed, especially attributes that are specific to authorization for communities of interest. Attributes shouldn’t be stored in multiple places, but aggregated identity information can itself be a security risk.

**Services Framework - Credential Management**

19. The sentence “An employee or contractor uses an authenticator with a password or cryptographic module to assert their identity.” Is incorrect. A password is an authenticator, it isn’t necessarily something used with an authenticator. Also, entities don’t use cryptographic modules to assert their identity, they use cryptographic modules to generate and protect authenticators.
20. The description of authenticators is incorrect. While a password is an authenticator, a private key is used to generate an authenticator by digitally signing a challenge. And a fingerprint isn’t an authenticator, the template generated from a fingerprint scan is the authenticator.
21. The steps in credential management are confusing, partly because identity proofing should be here and not in identity management. “Registration” should be replaced by identity proofing. Issuance should include the actual creation of the credential in addition to providing it to the entity. Maintenance needs more information for what it means to maintain a credential. No idea what withdrawing a credential means, revocation generally means making the credential invalid.
22. Shouldn’t credential validation be part of credential management? The validation itself happens as part of authentication, but managing a credential should require the ability to validate it.

**Services Framework - Access Management**

23. Recommend keeping provisioning as an access management element. Provisioning accounts is generally considered part of access management, and is better connected with policy administration than it is to attribute management. It would also make the statements about authorization clearer.
24. The definition of policy administration is incorrect. Policy administration isn’t about technology, it’s about business rules. Also, digital policy rules aren’t generally about “protected agency services” they are about access to agency resources.
25. In general, this section needs more narrative. Even for an ICAM expert, it is confusing. There are many ways to manage authorization, all of which are the “right” way for certain use cases. Access may be provisioned using roles, access may be dynamically determined real-time based on digital policy rules and user attributes, or there may be other models used. While the FICAM Architecture doesn’t need to specify how access is determined, it should at least provide the reader with an understanding of what the options are.
26. The term “privileged user” is used by different communities to mean different things. NIST SP 800-53 and the FICAM Architecture appear to be specifically referring to IT Privileged Users such as system administrators who are different from functionally privileged users such as supervisors. Recommend using the term IT Privileged User for clarity.

**Services Framework - Federation**

27. NIST uses the term “Identity Provider” in SP 800-63, recommend using this term instead of “authentication broker” which is not a term I’ve seen before.
28. Federation should include more than just agency to agency interoperability.

**Services Framework - Governance**

29. The term “identity governance” is used in industry to encompass activities that are already included in identity management and access management as well as the analytics and mitigation services. Recommend not trying to redefine it here.
30. Shouldn’t access review be part of governance?

**Use Case 2 – Proof an Identity**

31. Unclear why IAL2 is being included – if the entire thing is being limited to Agency Enterprise ICAM and agencies are required a minimum of IAL3 for employees & contractors why is IAL2 included on this page?

**Use Case 3 – Manage the Entitlements Lifecycle**

32. What is the difference between an attribute pertaining to something like a role and an entitlement giving the same information?

**Use Case 4 – Create and Issue a Credential**

33. These (step 3 image and text) do not appear to align – what is the relationship between the individual presenting a 2nd ID or account # and generation & assignment of authenticator?

**Use Case 5 – Issue a Derived Credential**

34. The last step again appears to be different steps - Instead of “Aggregate identity data to create a complete identity profile.” Maybe “Record information about new derived credential in user’s identity records.”

**Use Case 6 – Manage the Credential Lifecycle**

35. Under Renew a Credential – the final step should be to update User records with the new credential so that any application accounts tied to the old credential are appropriated updated as well (or grant or update access)

**Component Examples**

36. Don’t understand this section. From the title I would expect to see links to documentation or other resources that have been published by agencies. Instead it seems to be a collection of additional information related to some of the services framework elements. Consider relabeling and reworking this section. Information specific to elements of the services framework should be included on the related pages of the services framework itself. Also consider reaching out to agencies to identify resource they may have published and add links to those resources (e.g., the DoD recently published an Enterprise ICAM Reference Design which is posted to https://dodcio.defense.gov/library)
37. Federation is completely missing from this section. But federation is a critical element for ICAM. Need to better address federation, both between agencies and between agencies and their mission partners and constituents

**Standards & Policies**

38. Consider adding the IDEA act to the list of laws

**Comment by chekm8** [comment]
I'd like to preface this with I am a consumer of the FICAM v2 information.  I found it very helpful to level set with various groups on common IAM terminology.  I have many of the same thoughts that you have already articulated and will just stress on some of your points where I agree or disagree:

1:  I definitely echo this; we need to extend this to mission partners and other constituents

14: I respectfully disagree with you moving identity proofing to credential management.  You may have a process to identity proof someone without ever issuing a credential.  For Example. as a new hire to a company, the company may ask for information to prove that person is who they say they are (Drivers license, SSN Card, etc.) which flows into the identity solution well before a credential is ever issued.

15/23: I completely agree with you on this.  Provisioning, by definition, deals with accounts and should be under account management.

24: I agree again, this seems to have been redefined from the V2 version.   Policy Administration in the world of Access Management is about the rules.

26: "Privileged Access Management" section seems out of place, I know auditors always have a field day with this one and we have STIGs that recommend separate accounts, but this is really a variation on an identity if you want to keep things separate or possibly as simple as an alternate role a user is operating under.  

31: Another reason I think identity proofing needs to remain with identity management.  IAL2 allows for either remote or physically-present identity proofing, which some of our constituents will require.

It looks as if the "Entitlement Management" capability within Access Management was removed.  I looked as this as the capability that came before Provisioning occurred, where someone would manage a request prior to granting/revoking access.  Where would this fall in the new framework?  Why was it removed?

**Comment by lachellel** [comment]
> 1: I definitely echo this; we need to extend this to mission partners and other constituents
I believe we are in agreement that mission partners **and** other constituents (i.e. consumer or public as referenced in OMB M 19-17) have IAM needs.  However, there are different patterns, processes, and **policies** that need to be considered for each mission and constituents.  The intent is to have this revision be focused on the enterprise architecture model encompassing the baseline enterprise ICAM use cases for each agency, and to have an "overlay" or similar that is specific to interactions with consumers in a later phase.    Enterprise IAM vs Consumer IAM is common.    

> 15/23: I completely agree with you on this. Provisioning, by definition, deals with accounts and should be under account management.

This was debated in a few working sessions.  The model is fluid.  V2 had provisioning referenced in both service areas - and it was noted in submitted comments that this was confusing.  For developing the agency enterprise roadmaps and solution architectures, provisioning can be in either.       

> 26: "Privileged Access Management" section seems out of place, I know auditors always have a field day with this one and we have STIGs that recommend separate accounts, but this is really a variation on an identity if you want to keep things separate or possibly as simple as an alternate role a user is operating under.

PAM was added to align with common agency operating models, executive branch CDM deployments and use cases, and the separate CIO FISMA metrics (etc) for privileged.

**Comment by idmken** [comment]
I think we addressed these in v3.1 @sarahdobson

**Comment by sarahdobson** [comment]
**General Comments**

1. Updated scope statements in the playbook to clearly state NPEs and non-federal constituents are not included. Defer this change to future updates.
2. Disagree - no change.

**Introduction**

3. Reverted to 3.0 verbiage - it's an architecture.
4. Disagree - no change.
5. Made the Identity Management description more descriptive and updated related graphics.
6. Out of scope for this update.
7. Combined ICAM definitions and added the new ICAM definition to the conceptual diagram.
8. Updated the Federation definition and related graphics.
9. Updated communities and audiences to be more descriptive.
10. Reverted to & improved original background statements from v3.0

**Goals and Objectives**

11. Updated goal & related graphics to "Enable missions to efficiently deliver services."
12. Defer - out of scope for this update.
13. Disagree - these goals align with Cloud Smart and application rationalization, as well as CAP goals.

**Services Framework - Identity Management**

14. Restated Identity Proofing definition and updated related graphics: "Use identity attributes to connect a digital identity to a real-world entity."
15. Defer - this came up in working sessions.
16. Disagree. Added a keyword.
17. Changed to "Your identity remains the same over time, though it evolves as your attributes change, such as when you get a promotion, change your name receive additional training, or retire." Changed Deactivation definition to "Deactivate or remove enterprise identity records" in text and graphic.
18. Shortened to "Agencies should manage identity attributes as centrally as possible and distribute them as needed."

**Services Framework - Credential Management**

19. Aligned content with NIST definitions.
20. Defer to future update.
21. Changed "Issuance" to "Generation & Issuance"
22. Defer to future update.

**Services Framework - Access Management**

23. Defer - this came up in working sessions.
24. Changed "Policy administration" to "digital policy administration."
25. Added access control models.
26. Disagree - using FISMA & NIST standards for privileged users.

**Services Framework - Federation**

27. Defer to a future update.
28. Updated Federation definition, but kept small scope.

**Services Framework - Governance**

29. Disagree - aligned with industry standards.
30. Added access recertification to the keywords.

**Use Case 2 – Proof an Identity**

31. Updated to "There are three IALs; however, federal agencies require a minimum of IAL2 for employees or contractors with recurring access to government resources, so these use cases do not include IAL1."

**Use Case 3 – Manage the Entitlements Lifecycle**

32. Updated example with attribute reference.

**Use Case 4 – Create and Issue a Credential**

33. Changed text to "Generate and assign the authenticator to the individual."

**Use Case 5 – Issue a Derived Credential**

34. Changed text to "Generate the derived authenticator and note the change in the user's enterprise identity record."

**Use Case 6 – Manage the Credential Lifecycle**

35. Changed text to "The system issues a new credential to the employee or contractor, and updates the associated enterprise identity record."

**Component Examples**

36. Renamed "Components" to "System Components"
37. Defer to a future update.

**Standards & Policies**

38. Defer to a future update.
