### ISSUE TITLE
Content Feedback - DoD CIO

### ISSUE THREAD

**Issue by sarahdobson** [GSA/ficam-arch#172]
Comments from #171 not addressed by #170

**Introduction**

1. Identity management isn't about how attributes are used.  Identity management is the set of practices that allow an organization to establish, maintain, and terminate identities.

**Services Framework - Identity Management**

2. DoD uses the term "identity resolution" for the process of determining if two distinct digital identities belong to the same real world entity. "Identity aggregation" implies other activities that could cause concern with privacy experts. Recommend using the term "identity resolution" instead of "identity aggregation."
3. Agencies should make decisions for where attributes should be stored based on mission need.

**Services Framework - Credential Management**

4. If identity proofing is moved from identity management to credential management, then the confusing step of "registration" which is currently in credential management can be removed. If the identity itself is managed, it doesn't need to be registered again.
5. The process of creating a credential is missing from the definition of credential issuance.
6. Credentials aren't "withdrawn," they are either revoked or they expire. Wherever possible, the FICAM Architecture should use industry standard terminology and not create new unnecessary concepts.

**Services Framework - Federation**

7. Federal agencies interoperate with mission partners and constituents, and may federate identities, attributes, and credentials to support these interactions as well.

**Component Examples and Use Cases**

8. What is the intended distinction between examples and use cases? Need better clarification for these sections.

**Comment by idmken** [comment]
I think we included these in v3.1

**Comment by sarahdobson** [comment]
**Introduction**

1. Expanded Identity Management definition.

**Services Framework - Identity Management**

2. Added Identity Resolution keyword to the service definitions.
3. Shortened to "Agencies should manage identity attributes as centrally as possible and distribute them as needed."

**Services Framework - Credential Management**

4. Disagree.
5. Changed to "Generation & Issuance."
6. Streamlined language.

**Services Framework - Federation**

7. Consumer IAM is out of scope for v3.1.

**Component Examples and Use Cases**

8. Updated "Component Examples" to "System Component Examples" for clarity.
