### ISSUE TITLE
Privileged Access Management

### ISSUE THREAD

**Issue by sarahdobson** [GSA/ficam-arch#174]
#### Description of Issue: ####
Community feedback

#### Details of Issue: ####
Services Framework: The "vision" for Privileged Access Management seems limited.

**Comment by idmken** [comment]
@sarahdobson can you check which issues were addressed in v3.1 and close them?

**Comment by idmken** [comment]
I think this was fixed in v3.1

**Comment by sarahdobson** [comment]
We revisited this definition and aligned with FISMA metrics and NIST SPs.
