### ISSUE TITLE
Expanding use case for "Create and Issue Derived PIV"

### ISSUE THREAD

**Issue by rich-ppti** [GSA/ficam-arch#23]
We talked about this briefly before.  We should incorporate Secure Token Services (STS) and other derived credential capabilities.  

In looking at the **Create and Issue Derived PIV** (http://gsa.github.io/ficam-arch/usecases/24_createderivedpiv/) use case, there is a scenario where an STS from a trusted network could obviate the need for a mobile device.   An example would be the STS leveraging  Windows authentication on a trusted environment to establish a derived PIV.   Conceptually, this would be an _Identity Provider_ acting on behalf of the individual and an STS is an operational example.

**Comment by lachellel** [comment]
@rich-ppti 

Interesting one.  Here's my thoughts: 

Derived PIV is a credential. 
STS is an assertion (ephemeral token) mechanism.  

to your point: STS could be referenced in an operational example, under one of the Access use cases?

**Comment by rich-ppti** [comment]
Access may make some sense.  But, the conversations I heard seem to assume (read require) an LOA 4 credential.  My concern is some  individuals may NOT have the ability to present an LOA 4 credential.

If an organizational entity establishes a trusted STS and asserts the individual's identity, can this be done such that the identity is trusted at the LOA 4 level?   

A target scenario is where the individual needs access to a resource (e.g., TSP account?), does not have a PIV but yet can access the resource via the organizations STS.  The access should treat this as an LOA 4 access .....

**Comment by jim-thomson** [comment]
In LOA math, there is no concept for adding two separate identities (in this case a user and an STS) to increase the LOA. LOAs are defined in 800-63-2 as a low watermark approach - the strength is only as strong as its weakest link, for that user. Derived PIV, in my opinion, has done a lot of hand waving to explain why they are still LOA4, in all cases. This includes a USB or SIM card that can be easily separated from the device.

**Comment by lachellel** [comment]
This set of comments is still valid for updates to the use cases / architecture diagrams. 

Options:
- Consider removing derived piv **entirely**
- Replace with derived ? (word reference to nist sp)
- Focus on the small f federation / assertion model, and plug and play authenticators associated with the **enterprise** user via enterprise access managers (enterprise idp / sts / etc)

**Comment by lachellel** [comment]
addressed during architecture update working sessions  - closing
