### ISSUE TITLE
Add me to the repository

### ISSUE THREAD

**Issue by sph2sail** [GSA/ficam-arch#45]
Can I be added to the repository so I can clone it down to my laptop?  Or is web only the policy?

Thanks,
Steve Howard

**Comment by lachellel** [comment]
@sph2sail 

Hi Steve!  It's not web / gui only policy.  You should be able to _clone a read only copy_ to your local laptop - however, you won't have permissions to push changes directly (new branches, changes to _staging_ or _gh-pages_ branches, etc).  The _staging_ and _gh-pages_ branches are Protected to ensure everyone can review and discuss changes prior to merging.  

If you want to submit changes - you can Fork the repository first, then add any changes to your local fork, and submit pull requests back to the ficam-arch repo.     

If you can't clone the read only copy - let me know!

**Comment by lachellel** [comment]
@sph2sail 

Steve, were you able to access per the above? If so, let me know and I'll close the issue.  If you still can't clone or fork, let me know as well so I can revisit the settings!
