### ISSUE TITLE
Document History Section and Versioning

### ISSUE THREAD

**Issue by ronalfs2** [GSA/ficam-arch#46]
I recommend:
1. A version numbering scheme be implemented for the document that is incremented each time the document is officially updated.  The title of the document should reflect the version.
2. A document history be included, possibly in background section or having its own section that includes the version number, date of the version change and a summary of the changes.
3. Should 1 and/or 2 be applied, there should be a link or other ready means by which one could readily go to a previous version.

Rationale:  Absent the above, the document is problematic to cite to -- not only for research purposes, but also for pointing to in standards/policy documents and contracting instruments / agreements.

For example, agreements may point to the document as reflecting a common understanding on a particular date.  If the document is constantly changing without a versioning or document history record, agreeing parties might find it difficult to determine agreed to terms that were present on the date of the agreement -- absent github training.  Such training is likely too much of an ask for the target audience.

**Comment by lachellel** [comment]
@ronalfs2 

Agree.  By default versions are inherent in our use of a version control system here, but we should consider using the Release feature  - which will package up all the artifacts for each version into one bundle that is Versioned, for reference purposes.  

Do you think it would be acceptable to implement this when we migrate to a .gov site?  See the README - it's in progress and I'm pushing for **September** to have the **.gov**, which should be the reference used in all research, standards, policies and contracting agreements.

**Comment by lachellel** [comment]
https://github.com/GSA/ficam-arch/releases/tag/v3.0
