### ISSUE TITLE
Business process - move the words from the diagram header to web text?

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-arch#7]
http://gsa.github.io/ficam-arch/businessprocess/
ficam-arch/pages/ficam_business_process.md

The image itself contains the header words ("The diagram below...")

I think it might be more useful to remove the header words, put those in the body of the page, along with key (federal entities, business partners, customers) - and let the diagram just be the visual element.  

This way agencies or consumers can use the visual element and add their own words if they want to reuse. 

Thoughts

**Comment by tswicegood213** [comment]
On the other hand, leaving the "header text" in the image makes it easy for agencies to do a simple copy and paste without having to come up with their own intro text.  Keeps the image harmonious.

**Comment by lachellel** [comment]
I suggest we do both - we also need to consider 508 compliance.  

Moving text from images (e.g. header text etc) to body and intro that can be machine readable, and then also having a link to the full image for download.  

A " _Click < here > to download a copy of the diagram and introduction text_ "
