### ISSUE TITLE
Applications Diagram - Enterprise versus Customer

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-arch#8]
http://gsa.github.io/ficam-arch/applications/
ficam-arch/pages/ficam_applications.md

I think we should add another view to the Applications Diagrams.   
-  The Enterprise IAM versus the Customer IAM.  

Former is built to scale horizontally, with features meant for workflows, auditing, lots of integration points, etc. 

The latter is built to scale vertically - one or two types of users, all the same, same information, same processes, higher volume of users. 

From an Applications Diagram standpoint, you do want to keep them separate (separate IAM solution architectures, development approaches, and deployment).

**Comment by maxwellfunk** [comment]
Per October 2020 update to the architecture the applications view was updated to "system component examples" and could be applicable to multiple user populations (internal and external).  

Closing issue, feel free to reopen if issues remain.
