### ISSUE TITLE
Consistency of Template.md pages

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-arch#85]
#### Description of Issue: ####
The content contained in the Template.md pages (and their locations in the directory structures) is not consistent across the FICAM-Arch, FPKI-Guides, and PIV-Guides repos.

#### Details of Issue: ####
1.	The Template.md pages provide style and general instructions for those who need to write guides or information for the FICAM-Arch, FPKI-Guides, and PIV-Guides. 
2.	The content contained in the Template.md pages is not consistent across the 3 repos.  
3.	The Template.md pages are not located at the same directory structure level for all 3 repos. 

#### References (Docs, Links, Files): ####
https://github.com/GSA/ficam-arch/blob/staging/template.md
https://github.com/GSA/fpki-guides/blob/staging/template.md
https://github.com/GSA/fpki-guides/blob/staging/pages/template.md
https://github.com/GSA/piv-guides/blob/staging/pages/template.md

#### If a New Page or Content is Needed, Expected Outcomes: ####
1.	Make the content consistent for all Template.md pages:  sample outline for guides, the same style and general instructions, and Markdown syntax (style sheet).
2.	Place all Template.md pages in a consistent location in the directory structures for all 3 repos.

#### Link to the Content Page for Contributors: ####
None.

**Comment by clstmbrly** [comment]
@lachellel  The FICAM-Arch template and contribute files use a different naming convention than PIV-Guides and FPKI-Guides do.  For example, FICAM-Arch uses the name "ficam-contribute.md," but PIV- and FPKI-Guides use "contribute.md."  (All of the relevant FICAM-Arch files start with "ficam-...")  

Do want to preserve these names for FICAM-Arch or convert them to match those used in PIV- and FPKI-Guides?

Thanks much.

**Comment by lachellel** [comment]
@clstmbrly it makes sense to match for consistency and maintenance  +1

**Comment by clstmbrly** [comment]
Thanks! :-)
